In [1]:
from __future__ import absolute_import, division, print_function
%matplotlib inline

import os
import numpy as np
import PIL.Image as pil
import matplotlib.pyplot as plt

import torch
from torchvision import transforms

import networks
from utils import download_model_if_doesnt_exist

import cv2

In [4]:
path = './assets/depth_disp.npy'

data = np.load(path)

print(data)

[[[[0.80548525 0.8026325  0.8022328  ... 0.6989275  0.69725275
    0.7018425 ]
   [0.7890751  0.7865116  0.7852649  ... 0.6914954  0.68955344
    0.69420314]
   [0.7926634  0.7888872  0.78822684 ... 0.6869364  0.6847798
    0.6902782 ]
   ...
   [5.0181656  4.939097   4.935348   ... 5.1817255  5.176998
    5.1927047 ]
   [5.0583935  4.9826665  4.985914   ... 5.250618   5.250616
    5.2678766 ]
   [5.0975194  5.0353217  5.0374665  ... 5.305676   5.3068867
    5.322694  ]]]]


In [6]:
print(np.amax(data))

5.322694


In [9]:
print(np.amin(data))

0.27238566


In [8]:
# Import the necessary libraries
from PIL import Image
from numpy import asarray


# load the image and convert into
# numpy array
img = Image.open('./assets/depth_disp.jpeg')
numpydata = asarray(img)

# data
print(numpydata)


[[[ 25  16  59]
  [ 25  16  61]
  [ 25  16  61]
  ...
  [ 18  14  51]
  [ 18  14  51]
  [ 18  14  51]]

 [[ 25  16  61]
  [ 25  16  61]
  [ 25  16  61]
  ...
  [ 18  14  51]
  [ 18  14  51]
  [ 18  14  51]]

 [[ 25  16  63]
  [ 25  16  63]
  [ 25  16  63]
  ...
  [ 18  14  51]
  [ 18  14  51]
  [ 18  14  51]]

 ...

 [[251 252 192]
  [251 252 192]
  [251 252 192]
  ...
  [251 252 192]
  [251 252 192]
  [251 252 192]]

 [[251 252 192]
  [251 252 192]
  [251 252 192]
  ...
  [251 252 192]
  [251 252 192]
  [251 252 192]]

 [[251 252 192]
  [251 252 192]
  [251 252 192]
  ...
  [251 252 192]
  [251 252 192]
  [251 252 192]]]
